package com.sandy.dao;

import com.sandy.domain.Domain;

public interface DomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int insert(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int insertSelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    Domain selectByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Domain record);
}