package com.sandy.dao;

import com.sandy.domain.Method;

public interface MethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    int insert(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    int insertSelective(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    Method selectByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Method record);
}