package com.sandy.dao;

import com.sandy.domain.Method;

import java.util.List;

public interface MethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    int insert(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    int insertSelective(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    Method selectByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Method record);

    List<Method> selectMethodByDomainId(Long domainId);

}