package com.sandy.dao;

import com.sandy.domain.Testcase;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TestcaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int insertCase(@Param("methodId")Long methodId, @Param("userId")Long userId, @Param("content")String content);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int insertSelective(Testcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    Testcase selectByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Testcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Testcase record);

    List<Testcase> selectCaseByMethodId(Long methodId);

    List<Testcase> selectCaseByMethodIdAndUserId(Long methodId, Long userId);

    void updateByMethodAndUserId(@Param("methodId")Long methodId, @Param("userId")Long userId, @Param("content")String content);
}