package com.sandy.dao;

import com.sandy.domain.Testcase;

import java.util.List;

public interface TestcaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int insert(Testcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int insertSelective(Testcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    Testcase selectByPrimaryKey(Long sysno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Testcase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Testcase record);

    List<Testcase> selectCaseByMethodId(Long methodId);
}