package com.sandy.domain;

import java.io.Serializable;
import java.util.Date;

public class Method implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methods.sysno
     *
     * @mbggenerated
     */
    private Long sysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methods.resource_sysno
     *
     * @mbggenerated
     */
    private Long resourceSysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methods.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methods.method_params
     *
     * @mbggenerated
     */
    private String methodParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methods.method_desc
     *
     * @mbggenerated
     */
    private String methodDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methods.edit_time
     *
     * @mbggenerated
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table methods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methods.sysno
     *
     * @return the value of methods.sysno
     *
     * @mbggenerated
     */
    public Long getSysno() {
        return sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methods.sysno
     *
     * @param sysno the value for methods.sysno
     *
     * @mbggenerated
     */
    public void setSysno(Long sysno) {
        this.sysno = sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methods.resource_sysno
     *
     * @return the value of methods.resource_sysno
     *
     * @mbggenerated
     */
    public Long getResourceSysno() {
        return resourceSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methods.resource_sysno
     *
     * @param resourceSysno the value for methods.resource_sysno
     *
     * @mbggenerated
     */
    public void setResourceSysno(Long resourceSysno) {
        this.resourceSysno = resourceSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methods.method_name
     *
     * @return the value of methods.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methods.method_name
     *
     * @param methodName the value for methods.method_name
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methods.method_params
     *
     * @return the value of methods.method_params
     *
     * @mbggenerated
     */
    public String getMethodParams() {
        return methodParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methods.method_params
     *
     * @param methodParams the value for methods.method_params
     *
     * @mbggenerated
     */
    public void setMethodParams(String methodParams) {
        this.methodParams = methodParams == null ? null : methodParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methods.method_desc
     *
     * @return the value of methods.method_desc
     *
     * @mbggenerated
     */
    public String getMethodDesc() {
        return methodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methods.method_desc
     *
     * @param methodDesc the value for methods.method_desc
     *
     * @mbggenerated
     */
    public void setMethodDesc(String methodDesc) {
        this.methodDesc = methodDesc == null ? null : methodDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methods.edit_time
     *
     * @return the value of methods.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methods.edit_time
     *
     * @param editTime the value for methods.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Method other = (Method) that;
        return (this.getSysno() == null ? other.getSysno() == null : this.getSysno().equals(other.getSysno()))
            && (this.getResourceSysno() == null ? other.getResourceSysno() == null : this.getResourceSysno().equals(other.getResourceSysno()))
            && (this.getMethodName() == null ? other.getMethodName() == null : this.getMethodName().equals(other.getMethodName()))
            && (this.getMethodParams() == null ? other.getMethodParams() == null : this.getMethodParams().equals(other.getMethodParams()))
            && (this.getMethodDesc() == null ? other.getMethodDesc() == null : this.getMethodDesc().equals(other.getMethodDesc()))
            && (this.getEditTime() == null ? other.getEditTime() == null : this.getEditTime().equals(other.getEditTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSysno() == null) ? 0 : getSysno().hashCode());
        result = prime * result + ((getResourceSysno() == null) ? 0 : getResourceSysno().hashCode());
        result = prime * result + ((getMethodName() == null) ? 0 : getMethodName().hashCode());
        result = prime * result + ((getMethodParams() == null) ? 0 : getMethodParams().hashCode());
        result = prime * result + ((getMethodDesc() == null) ? 0 : getMethodDesc().hashCode());
        result = prime * result + ((getEditTime() == null) ? 0 : getEditTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysno=").append(sysno);
        sb.append(", resourceSysno=").append(resourceSysno);
        sb.append(", methodName=").append(methodName);
        sb.append(", methodParams=").append(methodParams);
        sb.append(", methodDesc=").append(methodDesc);
        sb.append(", editTime=").append(editTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}