package com.sandy.domain;

import java.io.Serializable;
import java.util.Date;

public class Method implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method.sysno
     *
     * @mbggenerated
     */
    private Long sysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method.domain_sysno
     *
     * @mbggenerated
     */
    private Long domainSysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method.edit_time
     *
     * @mbggenerated
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table method
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method.sysno
     *
     * @return the value of method.sysno
     *
     * @mbggenerated
     */
    public Long getSysno() {
        return sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method.sysno
     *
     * @param sysno the value for method.sysno
     *
     * @mbggenerated
     */
    public void setSysno(Long sysno) {
        this.sysno = sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method.domain_sysno
     *
     * @return the value of method.domain_sysno
     *
     * @mbggenerated
     */
    public Long getDomainSysno() {
        return domainSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method.domain_sysno
     *
     * @param domainSysno the value for method.domain_sysno
     *
     * @mbggenerated
     */
    public void setDomainSysno(Long domainSysno) {
        this.domainSysno = domainSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method.method
     *
     * @return the value of method.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method.method
     *
     * @param method the value for method.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method.desc
     *
     * @return the value of method.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method.desc
     *
     * @param desc the value for method.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method.edit_time
     *
     * @return the value of method.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method.edit_time
     *
     * @param editTime the value for method.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Method other = (Method) that;
        return (this.getSysno() == null ? other.getSysno() == null : this.getSysno().equals(other.getSysno()))
            && (this.getDomainSysno() == null ? other.getDomainSysno() == null : this.getDomainSysno().equals(other.getDomainSysno()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getEditTime() == null ? other.getEditTime() == null : this.getEditTime().equals(other.getEditTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSysno() == null) ? 0 : getSysno().hashCode());
        result = prime * result + ((getDomainSysno() == null) ? 0 : getDomainSysno().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getEditTime() == null) ? 0 : getEditTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysno=").append(sysno);
        sb.append(", domainSysno=").append(domainSysno);
        sb.append(", method=").append(method);
        sb.append(", desc=").append(desc);
        sb.append(", editTime=").append(editTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}