package com.sandy.domain;

import java.io.Serializable;
import java.util.Date;

public class Testcase implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.sysno
     *
     * @mbggenerated
     */
    private Long sysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.method_sysno
     *
     * @mbggenerated
     */
    private Long methodSysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.user_sysno
     *
     * @mbggenerated
     */
    private String userSysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.edit_time
     *
     * @mbggenerated
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table testcase
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.sysno
     *
     * @return the value of testcase.sysno
     *
     * @mbggenerated
     */
    public Long getSysno() {
        return sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.sysno
     *
     * @param sysno the value for testcase.sysno
     *
     * @mbggenerated
     */
    public void setSysno(Long sysno) {
        this.sysno = sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.method_sysno
     *
     * @return the value of testcase.method_sysno
     *
     * @mbggenerated
     */
    public Long getMethodSysno() {
        return methodSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.method_sysno
     *
     * @param methodSysno the value for testcase.method_sysno
     *
     * @mbggenerated
     */
    public void setMethodSysno(Long methodSysno) {
        this.methodSysno = methodSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.user_sysno
     *
     * @return the value of testcase.user_sysno
     *
     * @mbggenerated
     */
    public String getUserSysno() {
        return userSysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.user_sysno
     *
     * @param userSysno the value for testcase.user_sysno
     *
     * @mbggenerated
     */
    public void setUserSysno(String userSysno) {
        this.userSysno = userSysno == null ? null : userSysno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.content
     *
     * @return the value of testcase.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.content
     *
     * @param content the value for testcase.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.edit_time
     *
     * @return the value of testcase.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.edit_time
     *
     * @param editTime the value for testcase.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Testcase other = (Testcase) that;
        return (this.getSysno() == null ? other.getSysno() == null : this.getSysno().equals(other.getSysno()))
            && (this.getMethodSysno() == null ? other.getMethodSysno() == null : this.getMethodSysno().equals(other.getMethodSysno()))
            && (this.getUserSysno() == null ? other.getUserSysno() == null : this.getUserSysno().equals(other.getUserSysno()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getEditTime() == null ? other.getEditTime() == null : this.getEditTime().equals(other.getEditTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSysno() == null) ? 0 : getSysno().hashCode());
        result = prime * result + ((getMethodSysno() == null) ? 0 : getMethodSysno().hashCode());
        result = prime * result + ((getUserSysno() == null) ? 0 : getUserSysno().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getEditTime() == null) ? 0 : getEditTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testcase
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysno=").append(sysno);
        sb.append(", methodSysno=").append(methodSysno);
        sb.append(", userSysno=").append(userSysno);
        sb.append(", content=").append(content);
        sb.append(", editTime=").append(editTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}